version: '3.8'
services:
  backend:
    container_name: viajarapp-api
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./api/.env
    ports:
      - 4050:3001 # Puerto para el backend API
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - NODE_ENV=production
    networks:
      - proyectos-network

  qdrant:
    image: qdrant/qdrant:latest
    container_name: viajar-qdrant
    ports:
      - '6333:6333' # REST API
      - '6334:6334' # gRPC (opcional)
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped
    networks:
      - proyectos-network

volumes:
  qdrant_storage:
    driver: local

networks:
  proyectos-network:
    external: true
    name: proyectos-network
